---
title:                    FIO
tagline: 
description:              Foundation for Interwallet Operability
url: 
baseurl: 
lang:                     en
logo:                     /assets/img/logo.png
permalink:                "/:title/"

author:
  email:                  info@blacompany.com
  phone:                  +1-800-354-3434
  address:                2030 West River St. <br> New York 52304

favicon:                  /assets/img/favicon.ico

navbar:
  sticky:                 true
  
footer:
  copyright:              "&copy; 2020 FIO"
  link:
    title:                Privacy Policy
    url:                  /privacy-policy/

google_analytics:         GTM-WWSZ8NR

mailchimp:
  form_action:            https://some.list-manage.com/subscribe/post?u=jhgjhghjghjgjhg&id=hjjhjjhh
  hidden_name:            b_2e56c123105fsdfdsfsd2bd_e6e945b784

social_networks:
  telegram:               https://t.me/joinFIO
  discord:                https://discord.gg/pHBmJCc
  facebook:               https://www.facebook.com/officialFIO
  reddit:                 https://www.reddit.com/r/officialFIO
  linkedin:               https://www.linkedin.com/company/officialfio/
  twitter:                https://twitter.com/joinFIO

callout:
  heading:                Keep in Touch
  description:            Sign up for our monthly newsletter and join us on social!
  placeholder:            Enter Email Address
  
markdown:                 kramdown
highlighter:              rouge
plugins:
- jekyll-seo-tag

exclude:
- vendor
- ".bundle"
- ".sass-cache"
- ".jekyll-cache"
- config
- Gemfile
- Gemfile.lock
- node_modules
- log
- tmp
- Rakefile
- package.json
- package-lock.json
- CHANGELOG
- LICENSE
- README
- "/docs"
- "/assets/js/custom.js"

sass:
  style:                  compressed

livereload:               true

collections:
  testimonials:
    output: false
# defaults:
# - scope:
#     path: ''
#     type: collection_name
#   values:
#     layout: collection_name
# - scope:
#     path: ''
#     type: pages
#   values:
#     layout: 
